sudo: required
language: python
  - "3.6"

node_js: "10"

cache:
  - pip
  - yarn

env:
  global:
    - DISPLAY=':99.0'
    - YARN_VERSION='1.9.4'
    - MC_COMMIT='839cdad764d7' # https://hg.mozilla.org/mozilla-central/shortlog

notifications:
  slack:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - autoconf2.13
      - sshpass
      - p7zip-full
  artifacts:
    paths:
      - $HOME/firefox/mochitest.log

before_install:
  # Ensure the correct version of Python is used; borrowed from:
  # https://github.com/pre-commit/pre-commit/commit/e3ab8902692e896da9ded42bd4d76ea4e1de359d
  - pyenv global system 3.6

install:
  - pip install --user mercurial
  - python --version
  - node --version
  - . $HOME/.nvm/nvm.sh; nvm install 10.15.0; nvm use 10.15.0;
  - ./bin/ci/install-yarn
  - ./bin/ci/clone-gecko.sh
  - yarn
  - node bin/copy
  - ./bin/ci/build-firefox.sh
  - du -sh firefox
  - node ./bin/ci/check-file-sizes.js

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless
    browser_browser_toolbox_debugger
    browser_keybindings_01.js
    browser_toolbox_getpanelwhenready.js
    browser_markup_links_06.js
    browser_net_open_in_debugger.js
    browser_net_view-source-debugger.js
    browser_jsterm_autocomplete_in_debugger_stackframe.js
    browser_webconsole_eval_in_debugger_stackframe1.js
    browser_webconsole_eval_in_debugger_stackframe2.js
    browser_webconsole_location_debugger_link.js
    browser_webconsole_stacktrace_location_debugger_link.js
    browser_application_panel_debug-service-worker.js
    browser_webconsole_sourcemap_nosource
    browser_webconsole_context_menu_copy_entire_message.js
    browser_webconsole_context_menu_export_console_output_clipboard.js
    browser_webconsole_context_menu_copy_message_with_framework_stacktrace.js
    test_smart-trace
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless devtools/client/debugger
