sudo: required
dist: precise
language: python
  - "3.6"

node_js: "9"

cache:
  - pip
  - yarn

env:
  global:
    - DISPLAY=':99.0'
    - YARN_VERSION='0.24.5'
    - MC_COMMIT='48cc597db296' # https://hg.mozilla.org/mozilla-central/shortlog

notifications:
  slack:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - autoconf2.13
      - sshpass
      - p7zip-full
  artifacts:
    paths:
      - $HOME/firefox/mochitest.log

before_install:
  # Ensure the correct version of Python is used; borrowed from:
  # https://github.com/pre-commit/pre-commit/commit/e3ab8902692e896da9ded42bd4d76ea4e1de359d
  - pyenv global system 3.6

install:
  - pip install --user mercurial
  - . $HOME/.nvm/nvm.sh; nvm install 9; nvm use 9;
  - ./bin/ci/install-yarn
  - ./bin/ci/clone-gecko.sh
  - du -sh firefox
  - yarn
  - ./bin/ci/build-firefox.sh
  - python --version
  - node --version
  - du -sh firefox
  - node ./bin/copy-assets.js --mc ./firefox
  - node ./bin/copy-modules.js --mc ./firefox
  - ./bin/ci/build-firefox.sh
  - node ./bin/ci/check-file-sizes.js

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless devtools/client/debugger/new
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless
    browser_browser_toolbox_debugger
    browser_keybindings_01.js
    browser_toolbox_getpanelwhenready.js
    browser_markup_links_06.js
    browser_net_open_in_debugger.js
    browser_net_view-source-debugger.js
    browser_jsterm_autocomplete_in_debugger_stackframe.js
    browser_webconsole_eval_in_debugger_stackframe1.js
    browser_webconsole_eval_in_debugger_stackframe2.js
    browser_webconsole_location_debugger_link.js
    browser_webconsole_stacktrace_location_debugger_link.js
