language: python
node_js: "8"

cache:
  - pip
  - yarn


env:
  global:
    - DISPLAY=':99.0'
    - YARN_VERSION='0.24.5'
    - MC_COMMIT='c3d2757a5343' # https://hg.mozilla.org/mozilla-central/shortlog

notifications:
  slack:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      - autoconf2.13
      - sshpass
      - p7zip-full
  artifacts:
    paths:
      - $HOME/firefox/mochitest.log

install:
  - pip install --upgrade pip
  - pip install -U mercurial
  - . $HOME/.nvm/nvm.sh; nvm install stable; nvm use stable
  - ./bin/ci/install-yarn
  - ./bin/ci/clone-gecko.sh
  - du -sh firefox
  - yarn

before_script:
  - ./bin/ci/build-firefox.sh
  - sh -e /etc/init.d/xvfb start

script:
  - node --version
  - du -sh firefox
  - node ./bin/copy-assets.js --mc ./firefox
  - node ./bin/ci/check-file-sizes.js
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless devtools/client/debugger/new
  - ./node_modules/.bin/mochii --ci --mc ./firefox --headless
    browser_toolbox_debugger.js
    browser_keybindings_01.js
    browser_toolbox_getpanelwhenready.js
    browser_markup_links_06.js
    browser_net_open_in_debugger.js
    browser_net_view-source-debugger.js
    browser_jsterm_autocomplete_in_debugger_stackframe.js
    browser_webconsole_eval_in_debugger_stackframe1.js
    browser_webconsole_eval_in_debugger_stackframe2.js
    browser_webconsole_location_debugger_link.js
    browser_webconsole_stacktrace_location_debugger_link.js
    browser_browser_toolbox_debugger.js
